title: psll-lang performance
author: Marcin Konowalczyk
email: marcin.konow@lczyk.xyz
url:
baseurl: ""
description: Performance graphs for psll-lang

favicon: "logo.png" # name+extension of favicon (which must be put on the root folder)

sass:
  style: :compressed

exclude:
  - README.md