title: psll-lang performance
author: Marcin Konowalczyk
email: marcin.konow@lczyk.xyz
url: https://marcinkonowalczyk.github.io/psll-lang/
baseurl: "/psll-lang"
description: Performance graphs for psll-lang

favicon: "logo.png"

sass:
  style: :compressed

exclude:
  - README.md