#!/bin/bash

DIR=`dirname $0` # This script's directory
PSLL_COMPILER="$DIR/psll.py"
PYRA="$DIR/Pyramid-Scheme/pyra.rb"

# Compile psll into pyramid scheme
PSLL_FILE="$PWD/${1%.*}.psll"
PYRA_FILE="$PWD/${1%.*}.pyra"
echo "Compiling psll to pyramid scheme"
python $PSLL_COMPILER $PSLL_FILE -o $PYRA_FILE -f --no-compact # -v

if [ "$?" -eq 0 ]; then
    # Run pyramid scheme if compilation worked
    echo "Running the scheme"
    ruby $PYRA $PYRA_FILE "${@:2}"
fi


