<?xml  version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN"   "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0" >
<!-- Generated via Iro -->
<dict>
  <key>fileTypes</key>
  <array> 
    <string>psll</string>
   </array>
  <key>name</key>
  <string>psll</string>
  <key>patterns</key>
  <array> 
    <dict>
      <key>include</key>
      <string>#main</string>
    </dict>
   </array>
  <key>scopeName</key>
  <string>source.psll</string>
  <key>uuid</key>
  <string></string>
  <key>repository</key>
  <dict>
    <key>main</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#definition</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(?!\s)(set|loop|do|out|nil|chr|arg|range)(?=\s|\))</string>
          <key>name</key>
          <string>keyword.control.psll</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(?!\s)(\+|\*|-|\/|\^|=|&lt;=&gt;|#|\!|\?|_)(?=\s|\))</string>
          <key>name</key>
          <string>keyword.operator.psll</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\()</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.brackets.psll</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#main__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.brackets.psll</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>include</key>
          <string>#string</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#numeric</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#comment</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#space</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#other</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\[)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.brackets.psll</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#main__2</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\])</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.brackets.psll</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>comment</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(//.*)</string>
          <key>name</key>
          <string>comment.psll</string>
        </dict>
       </array>
    </dict>
    <key>definition</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(def)(\s+)([a-zA-Z][a-zA-Z0-9]*)</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.control.psll</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>invalid.psll</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>entity.name.function.psll</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(\()([a-zA-Z][a-zA-Z0-9]*)(\))</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.brackets.psll</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>entity.name.function.psll</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>punctuation.brackets.psll</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>main__1</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#main</string>
        </dict>
       </array>
    </dict>
    <key>main__2</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#string</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#numeric</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#comment</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#space</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#other</string>
        </dict>
       </array>
    </dict>
    <key>numeric</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>((?!\s)(?:\+|-)?\d+(?:\.\d+)?(?=\s|\)|\]))</string>
          <key>name</key>
          <string>constant.numeric.psll</string>
        </dict>
       </array>
    </dict>
    <key>other</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>((?!\s)[a-zA-Z][a-zA-Z0-9]*)</string>
          <key>name</key>
          <string>other.psll</string>
        </dict>
       </array>
    </dict>
    <key>space</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(\s)</string>
          <key>name</key>
          <string>invalid.psll</string>
        </dict>
       </array>
    </dict>
    <key>string</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>begin</key>
          <string>(\&quot;)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>string.punctuation.psll</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#string__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\&quot;)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>string.punctuation.psll</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>string__1</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(\\[\x{0022}\x{005c}nrt])</string>
          <key>name</key>
          <string>constant.character.escape.psll</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\\.)</string>
          <key>name</key>
          <string>constant.character.escape.psll</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([^\&quot;\x{005c}]+)</string>
          <key>name</key>
          <string>string.text.psll</string>
        </dict>
       </array>
    </dict>
  </dict>
</dict>
</plist>
