<?xml  version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN"   "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0" >
<!-- Generated via Iro -->
<dict>
  <key>fileTypes</key>
  <array> 
    <string>pyra</string>
    <string>pyr</string>
   </array>
  <key>name</key>
  <string>pyra</string>
  <key>patterns</key>
  <array> 
    <dict>
      <key>include</key>
      <string>#main</string>
    </dict>
   </array>
  <key>scopeName</key>
  <string>source.pyra</string>
  <key>uuid</key>
  <string></string>
  <key>repository</key>
  <dict>
    <key>main</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(\^)</string>
          <key>name</key>
          <string>punctuation.tip.pyra</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\/)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.edges.pyra</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#main__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\\)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.edges.pyra</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(-+)</string>
          <key>name</key>
          <string>keyword.base.pyra</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\s)</string>
          <key>name</key>
          <string>space.outside.pyra</string>
        </dict>
       </array>
    </dict>
    <key>keyword</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(\s?)(\+|\*|-|/|^|=|&lt;=&gt;|out|chr|arg|#|&quot;|!|\[|\]|set|do|loop|\?)(\s?)</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>space.inside.pyra</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>keyword.control.pyra</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>space.inside.pyra</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>main__1</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#keyword</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#numeric</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#other</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#space_inside</string>
        </dict>
       </array>
    </dict>
    <key>numeric</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(\s?)((?:\+|-)?\d+(?:\.\d+)?)(\s?)</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>space.inside.pyra</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>constant.numeric.pyra</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>space.inside.pyra</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>other</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(\s?)([a-zA-Z][a-zA-Z0-9]*)(\s?)</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>space.inside.pyra</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>other.pyra</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>space.inside.pyra</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>space_inside</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(\s)</string>
          <key>name</key>
          <string>space.inside.pyra</string>
        </dict>
       </array>
    </dict>
  </dict>
</dict>
</plist>
