name: publish

on:
  push:
    branches: [publish]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh && uv --version

      - name: Create virtual environment
        run: uv venv && source .venv/bin/activate

      - name: Build
        run: |
          uv pip install --upgrade wheel setuptools build twine
          python -m build
          twine check dist/*

      # --repository testpypi
      - name: Publish
        run: twine upload --verbose --username __token__ --password "$PYPI_TOKEN" dist/*
