name: test-commit

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Checkout Pyramid-Scheme
        run: git submodule update --init # --recursive

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh && uv --version

      - name: Create virtual environment
        run: uv venv && source .venv/bin/activate

      - name: Install test dependencies
        run: |
          uv pip install --upgrade wheel setuptools
          uv pip install --upgrade coverage pytest black mypy

      - name: Install psll
        run: uv pip install .

      - name: Check with black
        run: black --preview --check --verbose .

      - name: Check with mypy
        run: mypy --config-file ./mypy.ini psll

      - name: Run tests and coverage
        run: bash test.sh -e -c

      - name: Push to coveralls
        run: |
          uv pip install --upgrade coveralls
          coveralls debug --service=github

      # Performance check

      - name: Run performance check
        run: python ./perf/perf_ascii_trees.py result.perf && cat result.perf

      - name: Checkout psll-perf branch
        uses: actions/checkout@v3
        with:
          ref: psll-perf
          path: temp-perf

      - name: Append performance data
        run: |
          cd ./temp-perf
          cat ../result.perf | tail -n +2 | awk -v sha=$GITHUB_SHA '{ f = "./data/" $1 ".data"; $1 = sha; print >> f }'

      - name: Push to psll-perf
        run: |
          cd ./temp-perf
          git status
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -a -m "Automated report"
          git push
