name: test-pr

on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Checkout Pyramid-Scheme
        run: git submodule update --init # --recursive

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh && uv --version

      - name: Create virtual environment
        run: uv venv && source .venv/bin/activate

      - name: Install test dependencies
        run: |
          uv pip install --upgrade pip wheel setuptools
          uv pip install --upgrade coverage pytest black mypy

      - name: Install psll
        run: uv pip install "psll @ ."

      - name: Check with black
        run: black --preview --check --verbose .

      - name: Check with mypy
        run: mypy --config-file ./mypy.ini psll

      - name: Run tests (PR)
        run: bash test.sh -e
