name: tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python-version: [3.6, 3.9.0]
        
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install coverage
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run tests and coverage
      run: |
        bash run_coverage.sh # <- This runs tests for the main files too
        python -m unittest discover -p "test_examples.py" tests -v

    - name: Check with black
      if: "matrix.python-version == '3.6'"
      run: |
        pip install -Uq black
        black --check --verbose .

    - name: Push to coveralls
      if: "matrix.python-version == '3.6'"
      run: |
        pip install -Uq coveralls
        coveralls --service=github
