name: test-tox

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  test:
    strategy:
        matrix:
          os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}  

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Install uv and tox
        run: |
          pip install uv
          uv tool install tox --with tox-uv

      - name: Run tox
        run: uv tool run tox
